idf_component_register(SRCS "alarm_helpers.c" "motor_driver.c" "main.c" 
                    "display_driver.c" "lvgl_default_scr.c" 
                    "lvgl_medicines_list_scr.c" "medicines_managment.c"
                    "lvgl_add_medicine_scr.c" "lvgl_refill_medicine_scr.c"
                    "lvgl_alarm_scr.c"
                    INCLUDE_DIRS "." "include")

